CREATE TABLE "GCG_6321_CLAUSES"(
 "CLAUSE" VARCHAR(200),
 "TYPE" VARCHAR(100),
 "CLAUSE_NO" NUMERIC(5,0),
 "CUSTOMER" CHAR(6),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "INCLUDE_WO" BIT NOT NULL,
 "INCLUDE_PO" BIT NOT NULL,
 "INCLUDE_QUOTE" BIT NOT NULL,
 "NOTES" VARCHAR(400),
 "INCLUDE_SO" BIT NOT NULL );
